version: '2'
services:
    lztimer-app:
        image: lztimer
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://lztimer-postgresql:5432/lztimer
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lztimer-postgresql:
        extends:
            file: postgresql.yml
            service: lztimer-postgresql
